// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package vinyl

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createUserStmt, err = db.PrepareContext(ctx, createUser); err != nil {
		return nil, fmt.Errorf("error preparing query CreateUser: %w", err)
	}
	if q.deleteUserStmt, err = db.PrepareContext(ctx, deleteUser); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteUser: %w", err)
	}
	if q.deleteVinylStmt, err = db.PrepareContext(ctx, deleteVinyl); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteVinyl: %w", err)
	}
	if q.ensureOwnershipPlayStmt, err = db.PrepareContext(ctx, ensureOwnershipPlay); err != nil {
		return nil, fmt.Errorf("error preparing query EnsureOwnershipPlay: %w", err)
	}
	if q.getAllUserVinylPlaysStmt, err = db.PrepareContext(ctx, getAllUserVinylPlays); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllUserVinylPlays: %w", err)
	}
	if q.getAllVinylRecordsStmt, err = db.PrepareContext(ctx, getAllVinylRecords); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllVinylRecords: %w", err)
	}
	if q.getPrimaryReleaseIDStmt, err = db.PrepareContext(ctx, getPrimaryReleaseID); err != nil {
		return nil, fmt.Errorf("error preparing query GetPrimaryReleaseID: %w", err)
	}
	if q.getUserByIDStmt, err = db.PrepareContext(ctx, getUserByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByID: %w", err)
	}
	if q.getUserVinylPlaysStmt, err = db.PrepareContext(ctx, getUserVinylPlays); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserVinylPlays: %w", err)
	}
	if q.getVinylRecordByIDStmt, err = db.PrepareContext(ctx, getVinylRecordByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetVinylRecordByID: %w", err)
	}
	if q.insertVinylPlayStmt, err = db.PrepareContext(ctx, insertVinylPlay); err != nil {
		return nil, fmt.Errorf("error preparing query InsertVinylPlay: %w", err)
	}
	if q.listUsersStmt, err = db.PrepareContext(ctx, listUsers); err != nil {
		return nil, fmt.Errorf("error preparing query ListUsers: %w", err)
	}
	if q.nextPlayNumberStmt, err = db.PrepareContext(ctx, nextPlayNumber); err != nil {
		return nil, fmt.Errorf("error preparing query NextPlayNumber: %w", err)
	}
	if q.registerVinylUniqueStmt, err = db.PrepareContext(ctx, registerVinylUnique); err != nil {
		return nil, fmt.Errorf("error preparing query RegisterVinylUnique: %w", err)
	}
	if q.upsertVinylReleaseStmt, err = db.PrepareContext(ctx, upsertVinylRelease); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertVinylRelease: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createUserStmt != nil {
		if cerr := q.createUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createUserStmt: %w", cerr)
		}
	}
	if q.deleteUserStmt != nil {
		if cerr := q.deleteUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteUserStmt: %w", cerr)
		}
	}
	if q.deleteVinylStmt != nil {
		if cerr := q.deleteVinylStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteVinylStmt: %w", cerr)
		}
	}
	if q.ensureOwnershipPlayStmt != nil {
		if cerr := q.ensureOwnershipPlayStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing ensureOwnershipPlayStmt: %w", cerr)
		}
	}
	if q.getAllUserVinylPlaysStmt != nil {
		if cerr := q.getAllUserVinylPlaysStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllUserVinylPlaysStmt: %w", cerr)
		}
	}
	if q.getAllVinylRecordsStmt != nil {
		if cerr := q.getAllVinylRecordsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllVinylRecordsStmt: %w", cerr)
		}
	}
	if q.getPrimaryReleaseIDStmt != nil {
		if cerr := q.getPrimaryReleaseIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPrimaryReleaseIDStmt: %w", cerr)
		}
	}
	if q.getUserByIDStmt != nil {
		if cerr := q.getUserByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByIDStmt: %w", cerr)
		}
	}
	if q.getUserVinylPlaysStmt != nil {
		if cerr := q.getUserVinylPlaysStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserVinylPlaysStmt: %w", cerr)
		}
	}
	if q.getVinylRecordByIDStmt != nil {
		if cerr := q.getVinylRecordByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getVinylRecordByIDStmt: %w", cerr)
		}
	}
	if q.insertVinylPlayStmt != nil {
		if cerr := q.insertVinylPlayStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertVinylPlayStmt: %w", cerr)
		}
	}
	if q.listUsersStmt != nil {
		if cerr := q.listUsersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listUsersStmt: %w", cerr)
		}
	}
	if q.nextPlayNumberStmt != nil {
		if cerr := q.nextPlayNumberStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing nextPlayNumberStmt: %w", cerr)
		}
	}
	if q.registerVinylUniqueStmt != nil {
		if cerr := q.registerVinylUniqueStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing registerVinylUniqueStmt: %w", cerr)
		}
	}
	if q.upsertVinylReleaseStmt != nil {
		if cerr := q.upsertVinylReleaseStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertVinylReleaseStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                       DBTX
	tx                       *sql.Tx
	createUserStmt           *sql.Stmt
	deleteUserStmt           *sql.Stmt
	deleteVinylStmt          *sql.Stmt
	ensureOwnershipPlayStmt  *sql.Stmt
	getAllUserVinylPlaysStmt *sql.Stmt
	getAllVinylRecordsStmt   *sql.Stmt
	getPrimaryReleaseIDStmt  *sql.Stmt
	getUserByIDStmt          *sql.Stmt
	getUserVinylPlaysStmt    *sql.Stmt
	getVinylRecordByIDStmt   *sql.Stmt
	insertVinylPlayStmt      *sql.Stmt
	listUsersStmt            *sql.Stmt
	nextPlayNumberStmt       *sql.Stmt
	registerVinylUniqueStmt  *sql.Stmt
	upsertVinylReleaseStmt   *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                       tx,
		tx:                       tx,
		createUserStmt:           q.createUserStmt,
		deleteUserStmt:           q.deleteUserStmt,
		deleteVinylStmt:          q.deleteVinylStmt,
		ensureOwnershipPlayStmt:  q.ensureOwnershipPlayStmt,
		getAllUserVinylPlaysStmt: q.getAllUserVinylPlaysStmt,
		getAllVinylRecordsStmt:   q.getAllVinylRecordsStmt,
		getPrimaryReleaseIDStmt:  q.getPrimaryReleaseIDStmt,
		getUserByIDStmt:          q.getUserByIDStmt,
		getUserVinylPlaysStmt:    q.getUserVinylPlaysStmt,
		getVinylRecordByIDStmt:   q.getVinylRecordByIDStmt,
		insertVinylPlayStmt:      q.insertVinylPlayStmt,
		listUsersStmt:            q.listUsersStmt,
		nextPlayNumberStmt:       q.nextPlayNumberStmt,
		registerVinylUniqueStmt:  q.registerVinylUniqueStmt,
		upsertVinylReleaseStmt:   q.upsertVinylReleaseStmt,
	}
}
