// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package vinyl

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users(user_name) VALUES (?)
RETURNING user_id, user_name, date_created
`

func (q *Queries) CreateUser(ctx context.Context, userName string) (User, error) {
	row := q.queryRow(ctx, q.createUserStmt, createUser, userName)
	var i User
	err := row.Scan(&i.UserID, &i.UserName, &i.DateCreated)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE user_id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, userID int64) error {
	_, err := q.exec(ctx, q.deleteUserStmt, deleteUser, userID)
	return err
}

const deleteVinyl = `-- name: DeleteVinyl :exec
DELETE FROM vinyl_unique WHERE vinyl_id = ?
`

func (q *Queries) DeleteVinyl(ctx context.Context, vinylID int64) error {
	_, err := q.exec(ctx, q.deleteVinylStmt, deleteVinyl, vinylID)
	return err
}

const ensureOwnershipPlay = `-- name: EnsureOwnershipPlay :exec
INSERT OR IGNORE INTO vinyl_plays(user_id, vinyl_id, release_id, play, played_date)
VALUES (?, ?, ?, 0, ?)
`

type EnsureOwnershipPlayParams struct {
	UserID     int64  `db:"user_id"`
	VinylID    int64  `db:"vinyl_id"`
	ReleaseID  int64  `db:"release_id"`
	PlayedDate string `db:"played_date"`
}

func (q *Queries) EnsureOwnershipPlay(ctx context.Context, arg EnsureOwnershipPlayParams) error {
	_, err := q.exec(ctx, q.ensureOwnershipPlayStmt, ensureOwnershipPlay,
		arg.UserID,
		arg.VinylID,
		arg.ReleaseID,
		arg.PlayedDate,
	)
	return err
}

const getAllUserVinylPlays = `-- name: GetAllUserVinylPlays :many
SELECT
    user_id,
    vinyl_id,
    CAST(SUM(CASE WHEN play >= 1 THEN 1 ELSE 0 END) AS INTEGER) AS plays,
    CAST(MIN(played_date) AS TEXT) AS first_played,
    CAST(MAX(played_date) AS TEXT) AS last_played
FROM vinyl_plays
GROUP BY user_id, vinyl_id
`

type GetAllUserVinylPlaysRow struct {
	UserID      int64  `db:"user_id"`
	VinylID     int64  `db:"vinyl_id"`
	Plays       int64  `db:"plays"`
	FirstPlayed string `db:"first_played"`
	LastPlayed  string `db:"last_played"`
}

func (q *Queries) GetAllUserVinylPlays(ctx context.Context) ([]GetAllUserVinylPlaysRow, error) {
	rows, err := q.query(ctx, q.getAllUserVinylPlaysStmt, getAllUserVinylPlays)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllUserVinylPlaysRow{}
	for rows.Next() {
		var i GetAllUserVinylPlaysRow
		if err := rows.Scan(
			&i.UserID,
			&i.VinylID,
			&i.Plays,
			&i.FirstPlayed,
			&i.LastPlayed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllVinylRecords = `-- name: GetAllVinylRecords :many
SELECT
    vu.vinyl_id,
    vu.vinyl_title,
    vu.vinyl_artist,
    vu.master_id,
    vu.styles,
    vu.genres,
    CAST(substr(vr.released, 1, 4) AS INTEGER) AS vinyl_pressing_year,
    vr.country,
    vr.lowest_price AS recent_price,
    vr.released,
    vr.image_extension,
    vr.cover_raw_blob,
    vr.cover_embedding
FROM vinyl_unique vu
JOIN vinyl_release vr
    ON vr.vinyl_id = vu.vinyl_id
   AND vr.master_release = 1
ORDER BY vu.vinyl_artist ASC, vu.vinyl_title ASC
`

type GetAllVinylRecordsRow struct {
	VinylID           int64    `db:"vinyl_id"`
	VinylTitle        string   `db:"vinyl_title"`
	VinylArtist       string   `db:"vinyl_artist"`
	MasterID          *int64   `db:"master_id"`
	Styles            *string  `db:"styles"`
	Genres            *string  `db:"genres"`
	VinylPressingYear int64    `db:"vinyl_pressing_year"`
	Country           *string  `db:"country"`
	RecentPrice       *float64 `db:"recent_price"`
	Released          string   `db:"released"`
	ImageExtension    string   `db:"image_extension"`
	CoverRawBlob      []byte   `db:"cover_raw_blob"`
	CoverEmbedding    []byte   `db:"cover_embedding"`
}

func (q *Queries) GetAllVinylRecords(ctx context.Context) ([]GetAllVinylRecordsRow, error) {
	rows, err := q.query(ctx, q.getAllVinylRecordsStmt, getAllVinylRecords)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllVinylRecordsRow{}
	for rows.Next() {
		var i GetAllVinylRecordsRow
		if err := rows.Scan(
			&i.VinylID,
			&i.VinylTitle,
			&i.VinylArtist,
			&i.MasterID,
			&i.Styles,
			&i.Genres,
			&i.VinylPressingYear,
			&i.Country,
			&i.RecentPrice,
			&i.Released,
			&i.ImageExtension,
			&i.CoverRawBlob,
			&i.CoverEmbedding,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPrimaryReleaseID = `-- name: GetPrimaryReleaseID :one
SELECT release_id
FROM vinyl_release
WHERE vinyl_id = ? AND master_release = 1
LIMIT 1
`

func (q *Queries) GetPrimaryReleaseID(ctx context.Context, vinylID int64) (int64, error) {
	row := q.queryRow(ctx, q.getPrimaryReleaseIDStmt, getPrimaryReleaseID, vinylID)
	var release_id int64
	err := row.Scan(&release_id)
	return release_id, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT user_id, user_name, date_created FROM users WHERE user_id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, userID int64) (User, error) {
	row := q.queryRow(ctx, q.getUserByIDStmt, getUserByID, userID)
	var i User
	err := row.Scan(&i.UserID, &i.UserName, &i.DateCreated)
	return i, err
}

const getUserVinylPlays = `-- name: GetUserVinylPlays :many
SELECT
    user_id,
    vinyl_id,
    CAST(SUM(CASE WHEN play >= 1 THEN 1 ELSE 0 END) AS INTEGER) AS plays,
    CAST(MIN(played_date) AS TEXT) AS first_played,
    CAST(MAX(played_date) AS TEXT) AS last_played
FROM vinyl_plays
WHERE user_id = ?
GROUP BY user_id, vinyl_id
ORDER BY last_played DESC
`

type GetUserVinylPlaysRow struct {
	UserID      int64  `db:"user_id"`
	VinylID     int64  `db:"vinyl_id"`
	Plays       int64  `db:"plays"`
	FirstPlayed string `db:"first_played"`
	LastPlayed  string `db:"last_played"`
}

func (q *Queries) GetUserVinylPlays(ctx context.Context, userID int64) ([]GetUserVinylPlaysRow, error) {
	rows, err := q.query(ctx, q.getUserVinylPlaysStmt, getUserVinylPlays, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserVinylPlaysRow{}
	for rows.Next() {
		var i GetUserVinylPlaysRow
		if err := rows.Scan(
			&i.UserID,
			&i.VinylID,
			&i.Plays,
			&i.FirstPlayed,
			&i.LastPlayed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVinylRecordByID = `-- name: GetVinylRecordByID :one
SELECT
    vu.vinyl_id,
    vu.vinyl_title,
    vu.vinyl_artist,
    vu.master_id,
    vu.styles,
    vu.genres,
    CAST(substr(vr.released, 1, 4) AS INTEGER) AS vinyl_pressing_year,
    vr.country,
    vr.lowest_price AS recent_price,
    vr.released,
    vr.image_extension,
    vr.cover_raw_blob,
    vr.cover_embedding
FROM vinyl_unique vu
JOIN vinyl_release vr
    ON vr.vinyl_id = vu.vinyl_id
   AND vr.master_release = 1
WHERE vu.vinyl_id = ?
`

type GetVinylRecordByIDRow struct {
	VinylID           int64    `db:"vinyl_id"`
	VinylTitle        string   `db:"vinyl_title"`
	VinylArtist       string   `db:"vinyl_artist"`
	MasterID          *int64   `db:"master_id"`
	Styles            *string  `db:"styles"`
	Genres            *string  `db:"genres"`
	VinylPressingYear int64    `db:"vinyl_pressing_year"`
	Country           *string  `db:"country"`
	RecentPrice       *float64 `db:"recent_price"`
	Released          string   `db:"released"`
	ImageExtension    string   `db:"image_extension"`
	CoverRawBlob      []byte   `db:"cover_raw_blob"`
	CoverEmbedding    []byte   `db:"cover_embedding"`
}

func (q *Queries) GetVinylRecordByID(ctx context.Context, vinylID int64) (GetVinylRecordByIDRow, error) {
	row := q.queryRow(ctx, q.getVinylRecordByIDStmt, getVinylRecordByID, vinylID)
	var i GetVinylRecordByIDRow
	err := row.Scan(
		&i.VinylID,
		&i.VinylTitle,
		&i.VinylArtist,
		&i.MasterID,
		&i.Styles,
		&i.Genres,
		&i.VinylPressingYear,
		&i.Country,
		&i.RecentPrice,
		&i.Released,
		&i.ImageExtension,
		&i.CoverRawBlob,
		&i.CoverEmbedding,
	)
	return i, err
}

const insertVinylPlay = `-- name: InsertVinylPlay :exec
INSERT INTO vinyl_plays(user_id, vinyl_id, release_id, play, played_date)
VALUES (?, ?, ?, ?, ?)
`

type InsertVinylPlayParams struct {
	UserID     int64  `db:"user_id"`
	VinylID    int64  `db:"vinyl_id"`
	ReleaseID  int64  `db:"release_id"`
	Play       int64  `db:"play"`
	PlayedDate string `db:"played_date"`
}

func (q *Queries) InsertVinylPlay(ctx context.Context, arg InsertVinylPlayParams) error {
	_, err := q.exec(ctx, q.insertVinylPlayStmt, insertVinylPlay,
		arg.UserID,
		arg.VinylID,
		arg.ReleaseID,
		arg.Play,
		arg.PlayedDate,
	)
	return err
}

const listUsers = `-- name: ListUsers :many
SELECT user_id, user_name, date_created FROM users ORDER BY user_name ASC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.query(ctx, q.listUsersStmt, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.UserID, &i.UserName, &i.DateCreated); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextPlayNumber = `-- name: NextPlayNumber :one
SELECT COALESCE(MAX(play), 0) + 1
FROM vinyl_plays
WHERE user_id = ?
  AND vinyl_id = ?
  AND release_id = ?
`

type NextPlayNumberParams struct {
	UserID    int64 `db:"user_id"`
	VinylID   int64 `db:"vinyl_id"`
	ReleaseID int64 `db:"release_id"`
}

func (q *Queries) NextPlayNumber(ctx context.Context, arg NextPlayNumberParams) (int64, error) {
	row := q.queryRow(ctx, q.nextPlayNumberStmt, nextPlayNumber, arg.UserID, arg.VinylID, arg.ReleaseID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const registerVinylUnique = `-- name: RegisterVinylUnique :one
INSERT INTO vinyl_unique(
    vinyl_title,
    vinyl_artist,
    master_id,
    styles,
    genres
) VALUES (?, ?, ?, ?, ?)
ON CONFLICT
DO UPDATE SET vinyl_title = vinyl_title
RETURNING vinyl_id, vinyl_title, vinyl_artist, master_id, styles, genres
`

type RegisterVinylUniqueParams struct {
	VinylTitle  string  `db:"vinyl_title"`
	VinylArtist string  `db:"vinyl_artist"`
	MasterID    *int64  `db:"master_id"`
	Styles      *string `db:"styles"`
	Genres      *string `db:"genres"`
}

func (q *Queries) RegisterVinylUnique(ctx context.Context, arg RegisterVinylUniqueParams) (VinylUnique, error) {
	row := q.queryRow(ctx, q.registerVinylUniqueStmt, registerVinylUnique,
		arg.VinylTitle,
		arg.VinylArtist,
		arg.MasterID,
		arg.Styles,
		arg.Genres,
	)
	var i VinylUnique
	err := row.Scan(
		&i.VinylID,
		&i.VinylTitle,
		&i.VinylArtist,
		&i.MasterID,
		&i.Styles,
		&i.Genres,
	)
	return i, err
}

const upsertVinylRelease = `-- name: UpsertVinylRelease :one
INSERT INTO vinyl_release(
    vinyl_id,
    release_id,
    lowest_price,
    price_last_updated,
    country,
    notes,
    released,
    master_release,
    resource_uri,
    image_extension,
    cover_raw_blob,
    cover_embedding
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(vinyl_id, release_id)
DO UPDATE SET
    lowest_price = excluded.lowest_price,
    price_last_updated = excluded.price_last_updated,
    country = excluded.country,
    notes = excluded.notes,
    released = excluded.released,
    master_release = excluded.master_release,
    resource_uri = excluded.resource_uri,
    image_extension = excluded.image_extension,
    cover_raw_blob = excluded.cover_raw_blob,
    cover_embedding = excluded.cover_embedding
RETURNING vinyl_id, release_id, lowest_price, price_last_updated, country, notes, released, master_release, resource_uri, image_extension, cover_raw_blob, cover_embedding
`

type UpsertVinylReleaseParams struct {
	VinylID          int64    `db:"vinyl_id"`
	ReleaseID        int64    `db:"release_id"`
	LowestPrice      *float64 `db:"lowest_price"`
	PriceLastUpdated *string  `db:"price_last_updated"`
	Country          *string  `db:"country"`
	Notes            *string  `db:"notes"`
	Released         string   `db:"released"`
	MasterRelease    int64    `db:"master_release"`
	ResourceUri      string   `db:"resource_uri"`
	ImageExtension   string   `db:"image_extension"`
	CoverRawBlob     []byte   `db:"cover_raw_blob"`
	CoverEmbedding   []byte   `db:"cover_embedding"`
}

func (q *Queries) UpsertVinylRelease(ctx context.Context, arg UpsertVinylReleaseParams) (VinylRelease, error) {
	row := q.queryRow(ctx, q.upsertVinylReleaseStmt, upsertVinylRelease,
		arg.VinylID,
		arg.ReleaseID,
		arg.LowestPrice,
		arg.PriceLastUpdated,
		arg.Country,
		arg.Notes,
		arg.Released,
		arg.MasterRelease,
		arg.ResourceUri,
		arg.ImageExtension,
		arg.CoverRawBlob,
		arg.CoverEmbedding,
	)
	var i VinylRelease
	err := row.Scan(
		&i.VinylID,
		&i.ReleaseID,
		&i.LowestPrice,
		&i.PriceLastUpdated,
		&i.Country,
		&i.Notes,
		&i.Released,
		&i.MasterRelease,
		&i.ResourceUri,
		&i.ImageExtension,
		&i.CoverRawBlob,
		&i.CoverEmbedding,
	)
	return i, err
}
